---
a: [0.001]
b: [0.001, 0.01, 0.1, 1, 10, 100]
n_categories: [10000]
n_observations: [1, 10, 100, 1000]

---
a: [0.01]
b: [0.01, 0.1, 1, 10, 100]
n_categories: [10000]
n_observations: [1, 10, 100, 1000]

---
a: [0.1]
b: [0.1, 1, 10, 100]
n_categories: [10000]
n_observations: [1, 10, 100, 1000]

---
a: [1]
b: [1, 10, 100]
n_categories: [10000]
n_observations: [1, 10, 100, 1000]

---
a: [10]
b: [10, 100]
n_categories: [10000]
n_observations: [1, 10, 100, 1000]

---
a: [100]
b: [100]
n_categories: [10000]
n_observations: [1, 10, 100, 1000]

---
model: HBBM
model__method: "spectral"

---
model: HBBM
model__method: "mle"
